spring.application.name=web-empleos-backend
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/c5957026-1587-4782-82fe-9605c40565e1/v2.0
logging.level.org.springframework.web: DEBUG