package com.empleos.web_empleos_backend.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.time.LocalDateTime;

public class NotificacionTest {

    @Test
    void constructor_NoArgs_CreatesNotificationWithDefaults() {
        Notificacion notificacion = new Notificacion();
        assertNotNull(notificacion);
        assertNull(notificacion.getId());
        assertNull(notificacion.getDestinatario());
        assertNull(notificacion.getMensaje());
        // fechaCreacion se inicializa automáticamente
        assertNotNull(notificacion.getFechaCreacion());
    }

    @Test
    void constructor_WithParams_SetsFields() {
        String destinatario = "user123";
        String mensaje = "Nueva oferta disponible";
        
        Notificacion notificacion = new Notificacion(destinatario, mensaje);
        
        assertEquals(destinatario, notificacion.getDestinatario());
        assertEquals(mensaje, notificacion.getMensaje());
        assertNotNull(notificacion.getFechaCreacion());
        assertNull(notificacion.getId()); // ID is generated by JPA
    }

    @Test
    void settersAndGetters_WorkCorrectly() {
        Notificacion notificacion = new Notificacion();
        
        notificacion.setDestinatario("user456");
        assertEquals("user456", notificacion.getDestinatario());
        
        notificacion.setMensaje("Mensaje de prueba");
        assertEquals("Mensaje de prueba", notificacion.getMensaje());
        
        LocalDateTime fecha = LocalDateTime.now();
        notificacion.setFechaCreacion(fecha);
        assertEquals(fecha, notificacion.getFechaCreacion());
    }

    @Test
    void constructor_SetsCurrentDateTime() {
        LocalDateTime before = LocalDateTime.now();
        Notificacion notificacion = new Notificacion("user123", "mensaje");
        LocalDateTime after = LocalDateTime.now();
        
        assertNotNull(notificacion.getFechaCreacion());
        assertTrue(notificacion.getFechaCreacion().isAfter(before.minusSeconds(1)));
        assertTrue(notificacion.getFechaCreacion().isBefore(after.plusSeconds(1)));
    }

    @Test
    void getId_ReturnsCorrectValue() {
        Notificacion notificacion = new Notificacion();
        assertNull(notificacion.getId());
        // Note: ID setting is typically done by JPA, not through setter
        // In real scenarios, this would be set by the persistence framework
    }
}
